sudo: true

language: java

addons:
  apt:
    packages:
      - net-tools

jdk: oraclejdk8

env:
  - DOCKER_HOST=tcp://127.0.0.1:2375

services:
  - docker

before_install:
  - docker pull hechaol/ovs:2.9.0
  - export HOST_IP=$(/sbin/ifconfig docker0 | grep 'inet addr:' | cut -d':' -f2| cut -d' ' -f1)

script:
  - mvn clean verify -Dhost.ip=$HOST_IP

after_success:
  - mvn clean cobertura:cobertura-integration-test coveralls:report -Dhost.ip=$HOST_IP
